### ISSUE TITLE
newsletter page bugs

### ISSUE THREAD

**Issue by Graziel** [cakephp/community.cakephp.org#5]
im not sure where to post it so im posting it here

on page that links from newsletter 'View this email in your browser' http://us9.campaign-archive2.com/?u=f380de581acd576e7d802552a&id=11c4f1523c&e=754c71a580

on top menu
1) share doesnt work
2) translate doesnt show subitems
3) there is no meta in code that leads to RSS

**Comment by phpnut** [comment]
@Graziel We do not have control over how the site works. I will see if there is a way to disable some of these links. Our plan is to have the newsletters archived on cakephp.org and then we would have better control over the features offered.

**Comment by josegonzalez** [comment]
@Graziel seems like you have an adblocker installed. I disabled mine and the links work :)

**Comment by Graziel** [comment]
@josegonzalez yeah i thought so thats why i also tried it on Edge with same result

**Comment by HavokInspiration** [comment]
@phpnut As far as I know, you can only disable the full archive bar.
In the "Settings" menu of your List, under the "Publicity settings", there's a checkbox for that.

There is however no fine grained control over the links displayed in the bar.

**Comment by Graziel** [comment]
it would be great if someone else could verify this before doing anything to links cause as @josegonzalez pointed it can be my setup thats breaking that stuff (althou ive tried it with everything disabled / privacy mode / different browser)

**Comment by phpnut** [comment]
@Graziel have you tried it after the second newsletter went out? Everything seems to be working find on my side.

**Comment by Graziel** [comment]
@phpnut found the issue - ive disabled Adobe Flash on edge and on chrome, it appears that one of their .js files uses it 
```
/*!
 * zeroclipboard
 * The ZeroClipboard library provides an easy way to copy text to the clipboard using an invisible Adobe Flash movie, and a JavaScript interface.
 * Copyright 2012 Jon Rohan, James M. Greene, .
 * Released under the MIT license
 * http://zeroclipboard.github.com/ZeroClipboard/
 * v1.2.0-beta.1
```

it throws error and stops further js execution and thus disabling working menu :/

sorry for commotion
