### ISSUE TITLE
Include utility class all over the application

### ISSUE THREAD

**Issue by isaacrajaei** [cakephp/community.cakephp.org#6]
I have custom utility class that contains some methods for general use and it is located in src/Utility/UtilityClass.

I can include the Utility class in controller .e.g. 

    use App\Utility\ArrayUtil;

and then call the class in my controllers e.g.

    ArrayUtil::myMethod();

And it works. I need to include the UtilityClass in bootstrap so it applies all over the application so I can reuse it in models, templates and other controllers as well.

I tried to load it in config/bootstrap.php but I get this error:

> Error: Class 'ArrayUtil' not found

Any idea

**Comment by ADmad** [comment]
You have posted issue on wrong tracker.

That said issues tracker is not a help forum. The ticket tracker is reserved for possible
bugs and feature enhancements to the CakePHP framework. If you are
looking for help on how to implement a feature or to better understand
how to use the framework correctly, please visit one of the following:

[The CakePHP Manual](http://book.cakephp.org)
[The CakePHP online API](http://api.cakephp.org)
[Stackoverflow](http://stackoverflow.com/questions/tagged/cakephp) 

or the #cakephp channel on irc.freenode.net, where we will be more than
happy to help answer your questions.

Thanks!

**Comment by isaacrajaei** [comment]
Thank you @ADmad
